/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "1.25rem", sm: "1.5rem", md: "2rem", lg: "3rem", xl: "4rem", "2xl": "5rem" },
      screens: { "2xl": "1320px" },
    },
    extend: {
      fontFamily: {
        heading: ['"Playfair Display"', "Georgia", "serif"],
        sans: ['"DM Sans"', "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        surface: "hsl(var(--surface))",
        brand: {
          blue: "#1E5BFF",
          blue2: "#2D6CFF",
          violet: "#7C3AED",
          violet2: "#6B3CF5",
          navy: "#0B1437",
          ink: "#040815",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      backgroundImage: {
        "brand-gradient": "linear-gradient(135deg, #1E5BFF 0%, #6B3CF5 100%)",
        "brand-gradient-hover": "linear-gradient(135deg, #2D6CFF 0%, #7C3AED 100%)",
        "brand-soft": "radial-gradient(60% 60% at 50% 20%, rgba(30,91,255,0.18) 0%, rgba(124,58,237,0.10) 35%, rgba(0,0,0,0) 70%)",
      },
      boxShadow: {
        soft: "0 8px 30px rgba(11, 20, 55, 0.06)",
        hover: "0 24px 50px rgba(30, 91, 255, 0.18)",
        glass: "0 8px 32px rgba(11, 20, 55, 0.05)",
        ink: "0 24px 50px rgba(0,0,0,0.45)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-up": { "0%": { opacity: "0", transform: "translateY(12px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "blob": { "0%,100%": { transform: "translate(0,0) scale(1)" }, "33%": { transform: "translate(30px,-20px) scale(1.05)" }, "66%": { transform: "translate(-20px,15px) scale(0.97)" } },
        "shimmer": { "100%": { transform: "translateX(100%)" } },
        "marquee": { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.6s cubic-bezier(0.16,1,0.3,1) forwards",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "blob": "blob 14s ease-in-out infinite",
        "marquee": "marquee 38s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
